# Generated by Django 5.2 on 2025-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_course_difficulty_lesson_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='instructor_response',
            field=models.TextField(blank=True, null=True, verbose_name='Instructor Response'),
        ),
    ]
