# Generated by Django 5.2 on 2025-05-09 06:09

from django.db import migrations
from django.utils.text import slugify


def create_unique_slug(name):
    """
    Generate a slug from the name and ensure it's unique by appending a counter if needed.
    This is a simplified version for the migration.
    """
    base_slug = slugify(name)
    return base_slug


def add_course_categories(apps, schema_editor):
    """
    Adds common course categories to the database.
    """
    # Get the Category model from the migrations state
    Category = apps.get_model("courses", "Category")

    # Common categories for educational platforms
    categories = [
        {
            "name": "Programming & Development",
            "description": "Courses related to programming languages, software development, and web development.",
            "slug": "programming-development",
        },
        {
            "name": "Data Science & Analytics",
            "description": "Courses covering data analysis, machine learning, AI, and statistical methods.",
            "slug": "data-science-analytics",
        },
        {
            "name": "Business & Management",
            "description": "Courses on business strategy, leadership, management, and entrepreneurship.",
            "slug": "business-management",
        },
        {
            "name": "Design & Creativity",
            "description": "Courses about UI/UX design, graphic design, and creative arts.",
            "slug": "design-creativity",
        },
        {
            "name": "Mathematics",
            "description": "Courses covering various branches of mathematics and its applications.",
            "slug": "mathematics",
        },
        {
            "name": "Science & Engineering",
            "description": "Courses related to scientific disciplines and engineering principles.",
            "slug": "science-engineering",
        },
        {
            "name": "Language Learning",
            "description": "Courses for learning different languages and improving language skills.",
            "slug": "language-learning",
        },
        {
            "name": "Health & Wellness",
            "description": "Courses about health, nutrition, mental wellness, and personal care.",
            "slug": "health-wellness",
        },
        {
            "name": "Professional Skills",
            "description": "Courses focusing on skills useful in the workplace and career development.",
            "slug": "professional-skills",
        },
        {
            "name": "Personal Development",
            "description": "Courses related to self-improvement, productivity, and life skills.",
            "slug": "personal-development",
        },
        {
            "name": "Marketing & Communication",
            "description": "Courses about digital marketing, social media, content creation, and communication.",
            "slug": "marketing-communication",
        },
        {
            "name": "Finance & Accounting",
            "description": "Courses on financial literacy, investing, accounting, and money management.",
            "slug": "finance-accounting",
        },
    ]

    # Create each category
    for category_data in categories:
        Category.objects.create(**category_data)


def remove_course_categories(apps, schema_editor):
    """
    Removes the added categories (for rollback).
    """
    Category = apps.get_model("courses", "Category")

    # Get the category slugs from the list above
    category_slugs = [
        "programming-development",
        "data-science-analytics",
        "business-management",
        "design-creativity",
        "mathematics",
        "science-engineering",
        "language-learning",
        "health-wellness",
        "professional-skills",
        "personal-development",
        "marketing-communication",
        "finance-accounting",
    ]

    # Delete each category
    Category.objects.filter(slug__in=category_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_suggestion_instructor_response"),
    ]

    operations = [
        migrations.RunPython(add_course_categories, remove_course_categories),
    ]
