# Generated by Django 5.2 on 2025-05-09 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_suggestion_instructor_response'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='additional_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Data'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('HELPFUL', 'Helpful'), ('CONFUSED', 'Confused'), ('THANKS', 'Thanks'), ('INSIGHTFUL', 'Insightful')], max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('DISCUSSION_CREATED', 'Discussion Created'), ('COMMENT_ADDED', 'Comment Added'), ('REACTION_ADDED', 'Reaction Added'), ('SOLUTION_MARKED', 'Solution Marked'), ('DISCUSSION_VIEWED', 'Discussion Viewed'), ('DISCUSSION_CLOSED', 'Discussion Closed'), ('DISCUSSION_REOPENED', 'Discussion Reopened')], max_length=20, verbose_name='Activity Type'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_solution'], name='social_comm_is_solu_2edb45_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='social_comm_created_082b02_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['slug'], name='social_disc_slug_392173_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['status'], name='social_disc_status_dc566d_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['is_pinned', 'is_announcement', 'created_at'], name='social_disc_is_pinn_6515a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['type'], name='social_reac_type_4e8afb_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type'], name='social_user_activit_9f3265_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='social_user_created_ecb6f3_idx'),
        ),
    ]
